buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.2.2'
        // Do NOT have: classpath 'org.jetbrains.kotlin:kotlin-gradle-plugin:...'
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

ext {
    minSdkVersion = 23
    compileSdkVersion = 35
    targetSdkVersion = 35
}